[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
controller = ""
factory = ""
members = ""

[programs.devnet]
controller = "AtgYY2Aa91CGpuX9nX8U4ox7RevHD7N54LSJoDZzBxtE"
factory = "D29DJUN28bmSbMwQfeaBK2792HeSrDEsBg2uouD6q3Kr"
members = "9fMhjBNMKR6AhuELQiUpdov1B2Ec6ppNLGnBhiWFyUiS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_errors = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/04-factory_errors.ts"
